# Usa una imagen base de Java
FROM openjdk:11-jre-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR en el contenedor
COPY ProjectoDevops.jar /app/ProjectoDevops.jar

# Expone el puerto en el que escucha la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app/ProjectoDevops.jar"]
